version: '3'

services:
  message_store:
    build: ./message_store

    ports:
      - 80:80

    env_file:
      - .env      
      
  database:
    # Official Postgres image from DockerHub (last version)
    image: 'postgres:latest'

    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    ports:
      - 5432:5432

    env_file:
      - .env

    # The `volumes` tag allows to share a folder with container
    # Its syntax is as follows: [folder path on our machine]:[folder path to retrieve in the container]
    volumes:
      # Share the folder `.data` in root repository, with the default PostgreSQL data path.
      # It means that every time the repository is modifying the data inside
      # of `/var/lib/postgresql/data/`, automatically the change will appear in `.data`
      # You don't need to create the `.data` folder. Docker Compose will do it for you
      - ./db/.data/:/var/lib/postgresql/data/
      # Initialize messages & users
      - ./db/migrations/initialize_db.sql:/docker-entrypoint-initdb.d/init.sql
