from typing import Optional

from sqlalchemy import Column
from sqlalchemy import ForeignKey
from sqlalchemy import Integer
from sqlalchemy import PickleType
from sqlalchemy import String
from sqlalchemy.orm import Session

from .database import Base


class User(Base):
    __tablename__ = "app_user"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, index=True)


class Message(Base):
    __tablename__ = "message"

    id = Column(Integer, primary_key=True, index=True)
    content = Column(String, index=True)
    from_ = Column(Integer, ForeignKey("app_user.id"), name="from_", key="from")
    to = Column(Integer, ForeignKey("app_user.id"), name="to_")


class NotificationChannel(Base):
    __tablename__ = "notification_channel"

    id = Column(Integer, primary_key=True, index=True)
    client_correlator = Column(String, nullable=True, name="client_correlator")
    application_tag = Column(String, nullable=True, name="application_tag")
    channel_type = Column(String, name="channel_type")
    channel_data = Column(PickleType, name="channel_data")
    channel_life_time = Column(Integer, name="channel_life_time")
    callback_url = Column(String, name="callback_url")
    user = Column(Integer, ForeignKey("app_user.id"), name="user_id")


def get_user(db: Session, user_id: int) -> User:
    return db.query(User).filter(User.id == user_id).first()


def get_users(db: Session, skip: int = 0, limit: int = 100) -> list:
    return db.query(User).offset(skip).limit(limit).all()


def get_channel(db: Session, user_id: int, channel_id: int) -> NotificationChannel:
    return (
        db.query(NotificationChannel)
        .filter(
            NotificationChannel.user == user_id, NotificationChannel.id == channel_id
        )
        .first()
    )


# TO-DO do not save callback_url, it can be generated by the app
def create_notification_channel(
    db: Session,
    user_id: int,
    channel_type: str,
    channel_data: dict,
    channel_life_time: int,
    callback_url: str,  # <- proxy endpoint url
    client_correlator: Optional[str] = None,
    application_tag: Optional[str] = None,
) -> NotificationChannel:
    db_notification_channel = NotificationChannel(
        user=user_id,
        channel_type=channel_type,
        channel_data=channel_data,
        channel_life_time=channel_life_time,
        callback_url=callback_url,
        client_correlator=client_correlator,
        application_tag=application_tag,
    )
    db.add(db_notification_channel)
    db.commit()
    db.refresh(db_notification_channel)

    return db_notification_channel
